#!/usr/bin/env php
<?php

/*
|--------------------------------------------------------------------------
| Run The Artisan Application
|--------------------------------------------------------------------------
|
| When we run the console application, the current CLI command will be
| executed in this console and the response sent back to a terminal
| or another output device for the developers. Here goes nothing!
|
*/

require_once __DIR__.DIRECTORY_SEPARATOR.'main.php';
